import React from "react";
import { Link, useParams } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";

type Post = { slug:string; title:string; description:string; keywords:string; readTime:string; intro:string; sections:{heading:string; paragraphs:string[]}[] };

export const BLOG_POSTS: Post[] = [
  { slug:"elite-friends-ai-astrologer-and-friend", title:"Elite Friends: Aapka AI Astrologer Aur Bharosemand Dost", description:"Janiye Elite Friends kaise astrology insights aur friendly Hinglish conversations ko ek hi personal experience mein laata hai.", keywords:"Elite Friends astrologer, AI astrologer India, online astrologer friend, astrology chat Hinglish", readTime:"6 min read", intro:"Kabhi humein apne future ko samajhne ke liye astrologer chahiye hota hai, aur kabhi bina judgement ke baat sunne wala dost. Elite Friends isi idea par bana hai: ek AI-powered astrologer aur friendly companion jo aapse natural Hinglish mein baat karta hai.", sections:[
    {heading:"Astrologer bhi, dost bhi", paragraphs:["Elite Friends ka purpose sirf predictions dena nahi hai. Aap career, love, relationships, daily decisions aur emotional confusion jaise topics par friendly conversation kar sakte hain.","Astrology guidance ko ek direction ki tarah dekhein, guaranteed result ki tarah nahi. Bade financial, medical ya legal decisions qualified professionals ke saath verify karna zaroori hai."]},
    {heading:"Hinglish mein personal astrology conversation", paragraphs:["Formal language mein apni feelings explain karna mushkil ho sakta hai. Elite Friends aapki normal Hindi-English chat style ko samajhne ke liye design kiya gaya hai, jisse sawal poochna zyada natural lagta hai.","Aap seedha pooch sakte hain: career change ka time kaisa hai, relationship mein communication kaise improve karein, ya aaj ka din planning ke liye kaisa rahega."]},
    {heading:"WhatsApp par aasaan access", paragraphs:["Website se official WhatsApp button use karke conversation start ki ja sakti hai. Kisi unknown number, copied profile ya unofficial payment link par bharosa na karein.","Elite Friends ke characters AI-generated virtual profiles hain, real human astrologers nahi. Privacy policy padhein aur passwords, OTP, banking details ya identity documents kabhi share na karein."]}
  ]},
  { slug:"online-ai-astrologer-love-career-guidance", title:"Online AI Astrologer Se Love Aur Career Guidance Kaise Lein", description:"Love, relationship aur career questions ko online AI astrologer se sahi tarike se poochne ki practical Hinglish guide.", keywords:"online AI astrologer, love astrology guidance, career astrology India, astrologer chat online", readTime:"7 min read", intro:"Astrology session tab zyada useful hota hai jab sawal clear ho. Chahe topic love ho, career ho ya life direction, specific context dene se conversation focused aur practical ban sakti hai.", sections:[
    {heading:"Career ke liye clear questions poochhein", paragraphs:["Sirf “mera career kaisa rahega?” poochne ke bajay apni situation batayein: job switch, promotion, exam, business ya skill learning mein se kis decision par clarity chahiye.","AI astrologer ke response ko planning prompt ki tarah use karein. Apni qualifications, market conditions aur financial responsibilities ko decision mein priority dein."]},
    {heading:"Love aur relationship guidance", paragraphs:["Relationship questions mein doosre person ki private information share kiye bina apni concern explain karein. Communication, expectations aur boundaries par focused questions zyada healthy hote hain.","Astrology compatibility ek perspective de sakti hai, lekin consent, respect aur honest communication kisi bhi relationship ki real foundation hain."]},
    {heading:"Elite Friends conversation kaise start karein", paragraphs:["Elite Friends ki official website par companion select karein aur WhatsApp chat button tap karein. Apni preferred language aur topic pehle message mein bata dena helpful hai.","Example: “Mujhe career decision ko astrology perspective se samajhna hai, please simple Hinglish mein guide karo.”"]}
  ]},
  { slug:"daily-horoscope-rashifal-guide", title:"Daily Horoscope Aur Rashifal Ko Sahi Tarike Se Kaise Samjhein", description:"Daily horoscope aur rashifal padhte waqt kya dekhein, kya avoid karein, aur astrology insights ko daily planning mein kaise use karein.", keywords:"daily horoscope India, aaj ka rashifal, daily astrology guide, horoscope in Hinglish", readTime:"5 min read", intro:"Daily horoscope ek short cosmic weather report ki tarah ho sakta hai. Iska best use tab hota hai jab aap ise fear ya certainty ke bajay reflection aur planning ke tool ki tarah padhein.", sections:[
    {heading:"Rashifal direction deta hai, guarantee nahi", paragraphs:["General rashifal aapki sun sign ya moon sign ke broad patterns batata hai. Har person ki complete birth chart alag hoti hai, isliye ek hi prediction sab par exactly apply nahi hoti.","Positive prediction ko overconfidence aur challenging prediction ko fear ka reason na banayein. Dono ko mindful planning ke prompt ki tarah use karein."]},
    {heading:"Love, career aur health sections ka meaning", paragraphs:["Career section focus, communication ya timing ki theme suggest kar sakta hai. Love section emotional tone aur relationship communication par reflection de sakta hai.","Health-related horoscope medical diagnosis nahi hota. Symptoms ya health concerns ke liye qualified doctor se advice lein."]},
    {heading:"Elite Friends ke saath daily check-in", paragraphs:["Aap Elite Friends se daily astrology theme ko simple Hinglish mein explain karne aur uske basis par practical to-do list banane ko keh sakte hain.","Is tarah astrology insight friendly conversation aur real-world action ke beech ek useful bridge ban sakti hai."]}
  ]},
  { slug:"kundli-birth-chart-basics", title:"Kundli Aur Birth Chart Basics: Beginner’s Hinglish Guide", description:"Kundli, lagna, rashi, houses aur planets ke basic meaning ko simple Hinglish mein samjhein.", keywords:"kundli basics, birth chart India, lagna rashi meaning, astrology for beginners Hinglish", readTime:"8 min read", intro:"Kundli ya birth chart janam ke exact time aur place par planets ki symbolic position ka map hota hai. Beginners ke liye kuch basic concepts samajhna astrology conversation ko kaafi clear bana deta hai.", sections:[
    {heading:"Lagna, rashi aur houses", paragraphs:["Lagna chart ka starting point maana jata hai aur personality ke outer expression se associate kiya jata hai. Moon sign emotional patterns aur inner responses ko describe karne ke liye use hota hai.","Twelve houses life ke different areas—self, money, communication, home, creativity, work, partnership aur career—ko represent karte hain."]},
    {heading:"Planets aur aspects ka role", paragraphs:["Traditional Vedic astrology mein planets alag energies aur themes ko represent karte hain. Unki sign, house position aur mutual aspects ko saath dekhkar interpretation banti hai.","Ek placement ko isolation mein dekhkar final conclusion nikalna misleading ho sakta hai. Complete chart context important hota hai."]},
    {heading:"Accurate birth details kyun important hain", paragraphs:["Birth time mein chhota difference bhi lagna aur house positions ko affect kar sakta hai. Date, exact time aur birthplace jitna accurate hoga, chart discussion utni relevant ho sakti hai.","AI-generated astrology educational aur entertainment guidance hai. Life-changing decisions ke liye multiple reliable sources aur appropriate professionals ko consult karein."]}
  ]}
];

function Meta({post}:{post?:Post}) {
  const title=post ? `${post.title} | Elite Friends` : "Astrology Blog | Elite Friends - Aapka AI Astrologer Aur Dost";
  const description=post?.description || "Love, career, kundli, horoscope aur daily astrology ke practical Hinglish guides. Elite Friends aapka AI astrologer aur trusted digital dost hai.";
  const canonical=post ? `https://www.elitefriendss.com/blog/${post.slug}` : "https://www.elitefriendss.com/blog";
  const schema=post ? {"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.description,datePublished:"2026-08-10",dateModified:"2026-08-10",mainEntityOfPage:canonical,author:{"@type":"Organization",name:"Elite Friends"},publisher:{"@type":"Organization",name:"Elite Friends"}} : null;
  return <Helmet><title>{title}</title><meta name="description" content={description}/><meta name="keywords" content={post?.keywords || "astrology blog, AI astrologer India, horoscope Hinglish, Elite Friends"}/><meta name="robots" content="index, follow"/><link rel="canonical" href={canonical}/><meta property="og:title" content={title}/><meta property="og:description" content={description}/><meta property="og:type" content={post?"article":"website"}/><meta property="og:url" content={canonical}/>{schema&&<script type="application/ld+json">{JSON.stringify(schema)}</script>}</Helmet>;
}

export function BlogPage(){
  return <main className="flex-1 max-w-6xl w-full mx-auto px-4 py-10 md:py-14"><Meta/><section className="text-center max-w-3xl mx-auto mb-10"><div className="inline-flex items-center gap-2 bg-purple-50 border border-purple-100 text-purple-700 rounded-full px-4 py-2 text-xs font-bold uppercase tracking-wider"><Sparkles className="w-4 h-4"/> Astrology Guides</div><h1 className="text-3xl md:text-5xl font-extrabold text-slate-950 mt-4">Elite Friends: Aapka AI Astrologer Aur Dost</h1><p className="text-slate-600 mt-4 leading-relaxed">Love, career, kundli aur daily horoscope ko simple Hinglish mein samjhein. Astrology insights ke saath ek friendly companion jo aapki baat bhi sunta hai.</p></section><div className="grid md:grid-cols-2 gap-5">{BLOG_POSTS.map(post=><article key={post.slug} className="bg-white border border-slate-100 rounded-2xl p-6 shadow-sm flex flex-col"><p className="text-xs text-purple-600 font-bold uppercase tracking-wider">Astrology · {post.readTime}</p><h2 className="text-xl md:text-2xl font-extrabold text-slate-900 mt-2 leading-tight"><Link to={`/blog/${post.slug}`} className="hover:text-emerald-600">{post.title}</Link></h2><p className="text-sm text-slate-500 leading-relaxed mt-3 flex-1">{post.description}</p><Link to={`/blog/${post.slug}`} className="text-sm font-bold text-emerald-600 mt-5 inline-flex items-center gap-1">Poora article padhein <ArrowRight className="w-4 h-4"/></Link></article>)}</div></main>;
}

export function BlogArticlePage(){
  const {slug}=useParams(); const post=BLOG_POSTS.find(item=>item.slug===slug);
  if(!post)return <main className="flex-1 max-w-3xl mx-auto px-4 py-16"><h1 className="text-3xl font-bold">Article nahi mila</h1><Link to="/blog" className="text-emerald-600 mt-4 inline-block">Astrology Blog par wapas jaayein</Link></main>;
  return <main className="flex-1 max-w-3xl w-full mx-auto px-4 py-10 md:py-14"><Meta post={post}/><article><Link to="/blog" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-600"><ArrowLeft className="w-4 h-4"/> Astrology Blog</Link><p className="text-purple-600 font-bold text-xs uppercase tracking-wider mt-8">Elite Friends Astrology Guide</p><h1 className="text-3xl md:text-5xl font-extrabold text-slate-950 leading-tight mt-2">{post.title}</h1><p className="text-sm text-slate-400 mt-4">August 10, 2026 · {post.readTime}</p><p className="text-lg text-slate-600 leading-relaxed mt-8">{post.intro}</p><div className="space-y-8 mt-10">{post.sections.map(section=><section key={section.heading}><h2 className="text-2xl font-extrabold text-slate-900">{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph} className="text-slate-600 leading-relaxed mt-3">{paragraph}</p>)}</section>)}</div><aside className="bg-gradient-to-r from-purple-50 to-emerald-50 border border-purple-100 rounded-2xl p-6 mt-12"><h2 className="text-xl font-extrabold text-slate-900">Elite Friends se baat karein</h2><p className="text-sm text-slate-600 mt-2">Aapka AI astrologer aur trusted digital dost—love, career aur daily life ke sawalon par friendly Hinglish conversation.</p><Link to="/" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-700 mt-4">Apna dost choose karein <ArrowRight className="w-4 h-4"/></Link></aside></article></main>;
}
