import React from "react";
import { Link, useParams } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { ArrowLeft, ArrowRight } from "lucide-react";

type Post = { slug:string; title:string; description:string; keywords:string; readTime:string; intro:string; sections:{heading:string; paragraphs:string[]}[] };

export const BLOG_POSTS: Post[] = [
  { slug:"ai-companion-in-india", title:"AI Companion in India: A Practical Guide to Private Hinglish Chats", description:"Learn how an AI companion works, what to check before starting a private Hinglish chat, and how Elite Friends supports natural conversations.", keywords:"AI companion India, Hinglish AI companion, private AI chat, virtual friend India", readTime:"6 min read", intro:"AI companions are becoming a familiar way to talk, reflect, and unwind. For Indian users, the experience feels more natural when the conversation understands Hinglish and everyday messaging.", sections:[
    {heading:"What is an AI companion?", paragraphs:["An AI companion is a computer-generated conversational assistant designed for friendly, supportive interaction. It can respond to messages and adapt its tone to the conversation.","It is not a real person, therapist, doctor, or emergency service. Important health, legal, or financial decisions should always be checked with a qualified professional."]},
    {heading:"Why Hinglish makes conversation easier", paragraphs:["Many people naturally switch between Hindi and English while chatting. A Hinglish-focused companion can understand common phrases, informal spellings, and mixed-language questions.","Write the way you normally message a friend, then clarify whenever a response misses your meaning."]},
    {heading:"Privacy checks before you start", paragraphs:["Avoid sharing passwords, banking details, identification numbers, private photographs, or information that could be used to impersonate you. Review the privacy policy and available reset controls.","Elite Friends identifies its profiles as virtual AI entities. Read the privacy policy before beginning a conversation."]}
  ]},
  { slug:"how-to-chat-with-ai-friend-on-whatsapp", title:"How to Chat With an AI Friend on WhatsApp in Hinglish", description:"A step-by-step guide to starting a Hinglish AI friend conversation through WhatsApp, with practical privacy and safety tips.", keywords:"AI friend WhatsApp, Hinglish chat WhatsApp, virtual friend WhatsApp India, AI chatbot Hinglish", readTime:"5 min read", intro:"If WhatsApp is already where you talk with friends and family, starting an AI conversation there can feel more convenient than installing another app.", sections:[
    {heading:"Start from the official website", paragraphs:["Open the Elite Friends website, review the virtual profiles, and use the official WhatsApp button. Confirm the destination and avoid numbers shared by unverified pages.","A greeting such as “Hi, aaj Hinglish mein baat karte hain” gives the companion a clear language preference."]},
    {heading:"Set useful boundaries", paragraphs:["Tell the AI when you prefer short replies, a calmer tone, or a different language. Clear instructions make misunderstandings easier to correct.","Treat every response as AI-generated. Do not rely on chat for emergencies or professional advice, and never share sensitive account information."]},
    {heading:"Keep the conversation useful", paragraphs:["Ask open questions, share only the context needed, and correct wrong assumptions. Start a fresh topic or reset the conversation when it is no longer useful."]}
  ]},
  { slug:"ai-companion-privacy-safety-tips", title:"AI Companion Privacy and Safety: 8 Tips Before You Chat", description:"Protect your privacy when using an AI companion with eight practical tips for safer, more informed online conversations.", keywords:"AI companion privacy, AI chat safety, private virtual friend, safe AI chatbot tips", readTime:"7 min read", intro:"AI conversations can be convenient and engaging, but privacy still depends on the choices you make. These checks help reduce risk before and during a chat.", sections:[
    {heading:"1. Know that you are talking to AI", paragraphs:["A responsible service explains that its characters and replies are computer-generated. Do not assume a profile image or conversational tone represents a real person."]},
    {heading:"2. Keep sensitive information out of chat", paragraphs:["Never send passwords, one-time codes, card numbers, bank details, identity documents, exact addresses, or confidential workplace information."]},
    {heading:"3. Read the privacy policy", paragraphs:["Check what information is collected, why it is used, how long it may be retained, and how to contact support."]},
    {heading:"4. Verify official links", paragraphs:["Begin from the official domain and confirm external messaging destinations. Be cautious of copied profiles, unexpected payment requests, and unknown links."]},
    {heading:"5–8. Control, verify, and step away", paragraphs:["Use reset controls, verify important claims through reliable sources, protect your device and messaging account, and stop if a conversation becomes uncomfortable.","An AI companion is not a substitute for emergency help or qualified care. In immediate danger, contact local emergency services or a trusted person nearby."]}
  ]}
];

function Meta({post}:{post?:Post}) {
  const title=post ? `${post.title} | Elite Friends` : "AI Companion & Hinglish Chat Blog | Elite Friends";
  const description=post?.description || "Practical guides about AI companions, private Hinglish conversations, WhatsApp chat safety, and responsible virtual friendship.";
  const canonical=post ? `https://www.elitefriendss.com/blog/${post.slug}` : "https://www.elitefriendss.com/blog";
  const schema=post ? {"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.description,datePublished:"2026-08-10",dateModified:"2026-08-10",mainEntityOfPage:canonical,author:{"@type":"Organization",name:"Elite Friends"},publisher:{"@type":"Organization",name:"Elite Friends"}} : null;
  return <Helmet><title>{title}</title><meta name="description" content={description}/><meta name="keywords" content={post?.keywords || "AI companion blog, Hinglish AI chat, AI friend India"}/><meta name="robots" content="index, follow"/><link rel="canonical" href={canonical}/><meta property="og:title" content={title}/><meta property="og:description" content={description}/><meta property="og:type" content={post?"article":"website"}/><meta property="og:url" content={canonical}/>{schema&&<script type="application/ld+json">{JSON.stringify(schema)}</script>}</Helmet>;
}

export function BlogPage(){
  return <main className="flex-1 max-w-5xl w-full mx-auto px-4 py-10 md:py-14"><Meta/><div className="text-center max-w-2xl mx-auto mb-10"><p className="text-emerald-600 font-bold uppercase tracking-wider text-xs">Guides & Resources</p><h1 className="text-3xl md:text-5xl font-extrabold text-slate-950 mt-2">Elite Friends Blog</h1><p className="text-slate-500 mt-4">Helpful guides for safer, more natural AI conversations in Hinglish.</p></div><div className="grid md:grid-cols-3 gap-5">{BLOG_POSTS.map(post=><article key={post.slug} className="bg-white border border-slate-100 rounded-2xl p-6 shadow-sm flex flex-col"><p className="text-xs text-emerald-600 font-bold">{post.readTime}</p><h2 className="text-xl font-extrabold text-slate-900 mt-2 leading-tight"><Link to={`/blog/${post.slug}`} className="hover:text-emerald-600">{post.title}</Link></h2><p className="text-sm text-slate-500 leading-relaxed mt-3 flex-1">{post.description}</p><Link to={`/blog/${post.slug}`} className="text-sm font-bold text-emerald-600 mt-5 inline-flex items-center gap-1">Read article <ArrowRight className="w-4 h-4"/></Link></article>)}</div></main>;
}

export function BlogArticlePage(){
  const {slug}=useParams(); const post=BLOG_POSTS.find(item=>item.slug===slug);
  if(!post)return <main className="flex-1 max-w-3xl mx-auto px-4 py-16"><h1 className="text-3xl font-bold">Article not found</h1><Link to="/blog" className="text-emerald-600 mt-4 inline-block">Back to Blog</Link></main>;
  return <main className="flex-1 max-w-3xl w-full mx-auto px-4 py-10 md:py-14"><Meta post={post}/><article><Link to="/blog" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-600"><ArrowLeft className="w-4 h-4"/> Back to Blog</Link><p className="text-emerald-600 font-bold text-xs uppercase tracking-wider mt-8">AI Companion Guide</p><h1 className="text-3xl md:text-5xl font-extrabold text-slate-950 leading-tight mt-2">{post.title}</h1><p className="text-sm text-slate-400 mt-4">August 10, 2026 · {post.readTime}</p><p className="text-lg text-slate-600 leading-relaxed mt-8">{post.intro}</p><div className="space-y-8 mt-10">{post.sections.map(section=><section key={section.heading}><h2 className="text-2xl font-extrabold text-slate-900">{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph} className="text-slate-600 leading-relaxed mt-3">{paragraph}</p>)}</section>)}</div><div className="bg-emerald-50 border border-emerald-100 rounded-2xl p-6 mt-12"><h2 className="text-xl font-extrabold text-slate-900">Explore Elite Friends</h2><p className="text-sm text-slate-600 mt-2">Meet virtual AI companions designed for friendly Hinglish conversations.</p><Link to="/" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-700 mt-4">Visit home <ArrowRight className="w-4 h-4"/></Link></div></article></main>;
}
