import React from "react";
import { Link, useParams } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";

type Post = { slug:string; title:string; description:string; keywords:string; readTime:string; intro:string; sections:{heading:string; paragraphs:string[]}[] };

export const BLOG_POSTS: Post[] = [
  { slug:"elite-friends-ai-astrologer-and-friend", title:"Elite Friends: Your AI Astrologer and Trusted Friend", description:"Discover how Elite Friends brings astrology insights and friendly conversations together in one personal experience.", keywords:"Elite Friends astrologer, AI astrologer India, online astrologer friend, English astrology chat", readTime:"9 min read", intro:"Sometimes you need an astrologer to help you reflect on the future, and sometimes you need a friend who listens without judgment. Elite Friends combines both ideas in an AI-powered astrology companion.", sections:[
    {heading:"An astrologer and a friend", paragraphs:["Elite Friends is designed for more than predictions. You can have friendly conversations about career, love, relationships, daily decisions, and moments of emotional uncertainty.","Treat astrology as a source of reflection, not a guaranteed outcome. Always verify major financial, medical, or legal decisions with qualified professionals."]},
    {heading:"A personal astrology conversation", paragraphs:["Explaining personal feelings can be difficult. Elite Friends is designed to make astrology questions feel natural, conversational, and easy to explore.","You can ask about the timing of a career change, ways to improve communication in a relationship, or how to plan your day with greater awareness."]},
    {heading:"Easy access through WhatsApp", paragraphs:["Start from the official WhatsApp button on the Elite Friends website. Avoid unknown numbers, copied profiles, and unofficial payment links.","Elite Friends characters are AI-generated virtual profiles, not human astrologers. Read the privacy policy and never share passwords, one-time codes, banking details, or identity documents."]},
    {heading:"What you can discuss with Elite Friends", paragraphs:["You can explore broad themes involving career direction, relationship communication, personal habits, motivation, and daily planning. A useful conversation begins with a clear question and enough context for the AI to understand what kind of reflection you want.","You can also ask for a simple explanation of an astrology concept before discussing how it may relate to your situation. This approach makes the experience more educational and helps you separate symbolic interpretation from practical action."]},
    {heading:"How the friend-like experience helps", paragraphs:["Astrology terminology can feel technical or intimidating. A conversational format allows you to ask follow-up questions, request simpler wording, and examine a topic from more than one perspective. The goal is to help you reflect, not to pressure you into a decision.","A supportive tone can make it easier to organize thoughts, but it is still important to maintain healthy boundaries. An AI companion cannot replace close human relationships, professional counseling, or emergency support."]},
    {heading:"Getting a more useful response", paragraphs:["Begin with one topic at a time. Explain what decision you are considering, what options are available, and what outcome matters most to you. Ask the AI to separate astrology observations from practical suggestions so the two do not become confused.","Review every suggestion using your own judgment. If a claim appears too certain, ask for limitations and alternative interpretations. Responsible astrology leaves room for personal choice, changing circumstances, and evidence from the real world."]}
  ]},
  { slug:"online-ai-astrologer-love-career-guidance", title:"How to Ask an Online AI Astrologer About Love and Career", description:"A practical guide to asking an online AI astrologer clear questions about love, relationships, and career.", keywords:"online AI astrologer, love astrology guidance, career astrology India, astrologer chat online", readTime:"10 min read", intro:"An astrology conversation becomes more useful when your question is clear. Whether the topic is love, career, or life direction, specific context helps keep the guidance focused and practical.", sections:[
    {heading:"Ask clear career questions", paragraphs:["Instead of asking only, “How will my career go?”, explain whether you need clarity about a job change, promotion, exam, business decision, or new skill.","Use the AI astrologer’s response as a planning prompt. Give priority to your qualifications, market conditions, and financial responsibilities when making a decision."]},
    {heading:"Love and relationship guidance", paragraphs:["Explain your concern without sharing another person’s private information. Questions focused on communication, expectations, and boundaries are more constructive.","Astrological compatibility can offer one perspective, but consent, respect, and honest communication are the real foundations of a relationship."]},
    {heading:"How to start an Elite Friends conversation", paragraphs:["Choose a companion on the official Elite Friends website and tap the WhatsApp chat button. Mentioning your preferred language and topic in the first message can help.","Example: “I would like to explore my career decision from an astrology perspective. Please guide me in simple English.”"]},
    {heading:"Questions to ask about a job change", paragraphs:["Useful questions may include: What strengths should I focus on during this transition? Which risks deserve more attention? How can I prepare emotionally and financially before changing roles? These questions invite reflection without assuming that astrology can guarantee a result.","Compare the response with practical evidence such as salary, job stability, growth opportunities, location, workplace culture, and your long-term goals. Astrology may inspire a new angle, but your final decision should rest on complete information."]},
    {heading:"Questions to ask about a relationship", paragraphs:["Instead of asking whether a relationship is destined to succeed, ask how you can communicate more clearly, recognize recurring patterns, or create healthier boundaries. This keeps the conversation focused on actions within your control.","Avoid using astrology to label another person or justify controlling behavior. Compatibility readings should never override consent, safety, mutual respect, or direct communication between the people involved."]},
    {heading:"When to seek professional support", paragraphs:["An AI astrology conversation is not appropriate for diagnosing mental health conditions, handling abuse, responding to an emergency, or making complex legal and financial choices. In those situations, contact a qualified professional or a trusted support service.","If you feel overwhelmed, step away from predictions and focus on immediate, practical needs. The most responsible guidance recognizes its limits and encourages expert help when the situation requires it."]}
  ]},
  { slug:"daily-horoscope-rashifal-guide", title:"How to Read a Daily Horoscope Responsibly", description:"Learn what to consider when reading a daily horoscope and how to use astrology insights for thoughtful daily planning.", keywords:"daily horoscope India, daily horoscope guide, daily astrology planning, English horoscope", readTime:"10 min read", intro:"A daily horoscope can be viewed as a short cosmic weather report. It is most useful as a tool for reflection and planning rather than fear or certainty.", sections:[
    {heading:"A horoscope offers direction, not a guarantee", paragraphs:["A general horoscope describes broad patterns associated with a sun or moon sign. Every complete birth chart is different, so one prediction cannot apply to everyone in exactly the same way.","Do not let a positive prediction create overconfidence or a challenging one create fear. Use both as prompts for mindful planning."]},
    {heading:"Understanding love, career, and health sections", paragraphs:["A career section may suggest themes involving focus, communication, or timing. A love section may encourage reflection on emotions and relationship communication.","A health horoscope is not a medical diagnosis. Consult a qualified doctor about symptoms or health concerns."]},
    {heading:"A daily check-in with Elite Friends", paragraphs:["You can ask Elite Friends to explain a daily astrology theme in simple English and turn it into a practical to-do list.","In this way, astrology can become a useful bridge between friendly reflection and real-world action."]},
    {heading:"A simple morning horoscope routine", paragraphs:["Read the horoscope once and identify one constructive theme, such as patience, preparation, communication, or rest. Turn that theme into a small action you can realistically complete during the day.","Avoid repeatedly checking predictions for reassurance. A horoscope should not increase anxiety or prevent ordinary decisions. If reading it creates fear, take a break and return attention to facts, routines, and people you trust."]},
    {heading:"Why different horoscopes may disagree", paragraphs:["Different astrologers may use sun signs, moon signs, ascendants, planetary transits, or different interpretive traditions. Short online horoscopes also have limited space, so writers may emphasize different themes for the same day.","Disagreement does not mean you must search until you find the most positive prediction. Instead, notice the broad ideas that are genuinely relevant and ignore statements that do not fit your circumstances."]},
    {heading:"Use reflection questions instead of fear", paragraphs:["After reading a horoscope, ask: What is within my control today? Is there a conversation I should approach more carefully? What preparation would reduce avoidable stress? Reflection questions convert a vague prediction into responsible self-observation.","Your choices, environment, relationships, and opportunities have real influence on the day. Astrology can complement planning, but it should never replace common sense, verified information, or appropriate professional advice."]}
  ]},
  { slug:"kundli-birth-chart-basics", title:"Kundli and Birth Chart Basics: A Beginner’s Guide", description:"Understand the basic meaning of a kundli, ascendant, zodiac signs, houses, and planets in simple English.", keywords:"kundli basics, birth chart India, ascendant and zodiac meaning, astrology for beginners English", readTime:"8 min read", intro:"A kundli, or birth chart, maps the symbolic positions of planets at the exact time and place of birth. Understanding a few basic concepts can make astrology discussions much clearer for beginners.", sections:[
    {heading:"Ascendant, zodiac signs, and houses", paragraphs:["The ascendant is considered the starting point of a chart and is associated with outward expression. The moon sign is commonly used to explore emotional patterns and inner responses.","The twelve houses represent different areas of life, including identity, money, communication, home, creativity, work, partnerships, and career."]},
    {heading:"The role of planets and aspects", paragraphs:["In traditional Vedic astrology, planets represent different energies and themes. Interpretations consider their signs, house positions, and relationships with one another.","Drawing a final conclusion from one placement can be misleading. The context of the complete chart matters."]},
    {heading:"Why accurate birth details matter", paragraphs:["Even a small difference in birth time can affect the ascendant and house positions. Accurate date, time, and birthplace details can make a chart discussion more relevant.","AI-generated astrology is intended for educational and entertainment guidance. Consult reliable sources and appropriate professionals before making life-changing decisions."]},
    {heading:"The twelve houses at a glance", paragraphs:["The first house relates to identity and presentation, while the second is commonly associated with resources and values. The third covers communication and learning, and the fourth is linked with home, family, and emotional foundations.","The remaining houses explore creativity, routines, partnerships, shared resources, beliefs, career, communities, and private inner life. Their meaning is interpreted together with signs, planets, aspects, and the overall structure of the chart."]},
    {heading:"What planetary placements can describe", paragraphs:["Astrologers associate the Sun with identity and vitality, the Moon with emotional patterns, Mercury with communication, Venus with values and relationships, and Mars with drive and action. Jupiter and Saturn are often linked with growth, responsibility, structure, and long-term lessons.","These are symbolic frameworks rather than scientifically proven mechanisms. A thoughtful reading presents possibilities and patterns without claiming that one planet removes personal freedom or determines an unavoidable future."]},
    {heading:"How to prepare for a birth chart discussion", paragraphs:["Confirm your birth details, write down two or three focused questions, and note the real-life context behind them. Ask the astrologer or AI to explain unfamiliar terms and to distinguish broad chart themes from specific predictions.","Keep a record of insights that feel useful, then revisit them later with a critical mind. A good discussion should increase understanding and thoughtful choice, not create dependency, urgency, or fear."]}
  ]}
];

function Meta({post}:{post?:Post}) {
  const title=post ? `${post.title} | Elite Friends` : "Astrology Blog | Elite Friends - Your AI Astrologer and Friend";
  const description=post?.description || "Explore practical English guides about love, career, kundli, horoscopes, and daily astrology from Elite Friends, your AI astrologer and trusted digital friend.";
  const canonical=post ? `https://www.elitefriendss.com/blog/${post.slug}` : "https://www.elitefriendss.com/blog";
  const schema=post ? {"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.description,datePublished:"2026-08-10",dateModified:"2026-08-10",mainEntityOfPage:canonical,author:{"@type":"Organization",name:"Elite Friends"},publisher:{"@type":"Organization",name:"Elite Friends"}} : null;
  return <Helmet><title>{title}</title><meta name="description" content={description}/><meta name="keywords" content={post?.keywords || "astrology blog, AI astrologer India, English horoscope, Elite Friends"}/><meta name="robots" content="index, follow"/><link rel="canonical" href={canonical}/><meta property="og:title" content={title}/><meta property="og:description" content={description}/><meta property="og:type" content={post?"article":"website"}/><meta property="og:url" content={canonical}/>{schema&&<script type="application/ld+json">{JSON.stringify(schema)}</script>}</Helmet>;
}

export function BlogPage(){
  return <main className="ai-page flex-1 max-w-6xl w-full mx-auto px-4 py-10 md:py-14"><Meta/><section className="text-center max-w-3xl mx-auto mb-10"><div className="inline-flex items-center gap-2 bg-purple-50 border border-purple-100 text-purple-700 rounded-full px-4 py-2 text-xs font-bold uppercase tracking-wider"><Sparkles className="w-4 h-4"/> Astrology Guides</div><h1 className="text-3xl md:text-5xl font-extrabold text-slate-950 mt-4">Elite Friends: Your AI Astrologer and Friend</h1><p className="text-slate-600 mt-4 leading-relaxed">Explore love, career, kundli, and daily horoscopes in clear English with a friendly AI astrology companion that also listens.</p></section><div className="grid md:grid-cols-2 gap-5">{BLOG_POSTS.map(post=><article key={post.slug} className="bg-white border border-slate-100 rounded-2xl p-6 shadow-sm flex flex-col"><p className="text-xs text-purple-600 font-bold uppercase tracking-wider">Astrology · {post.readTime}</p><h2 className="text-xl md:text-2xl font-extrabold text-slate-900 mt-2 leading-tight"><Link to={`/blog/${post.slug}`} className="hover:text-emerald-600">{post.title}</Link></h2><p className="text-sm text-slate-500 leading-relaxed mt-3 flex-1">{post.description}</p><Link to={`/blog/${post.slug}`} className="text-sm font-bold text-emerald-600 mt-5 inline-flex items-center gap-1">Read the full article <ArrowRight className="w-4 h-4"/></Link></article>)}</div></main>;
}

export function BlogArticlePage(){
  const {slug}=useParams(); const post=BLOG_POSTS.find(item=>item.slug===slug);
  if(!post)return <main className="ai-page flex-1 max-w-3xl mx-auto px-4 py-16"><h1 className="text-3xl font-bold">Article not found</h1><Link to="/blog" className="text-emerald-600 mt-4 inline-block">Return to the Astrology Blog</Link></main>;
  return <main className="ai-page flex-1 max-w-3xl w-full mx-auto px-4 py-10 md:py-14"><Meta post={post}/><article><Link to="/blog" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-600"><ArrowLeft className="w-4 h-4"/> Astrology Blog</Link><p className="text-purple-600 font-bold text-xs uppercase tracking-wider mt-8">Elite Friends Astrology Guide</p><h1 className="text-3xl md:text-5xl font-extrabold text-slate-950 leading-tight mt-2">{post.title}</h1><p className="text-sm text-slate-400 mt-4">August 10, 2026 · {post.readTime}</p><p className="text-lg text-slate-600 leading-relaxed mt-8">{post.intro}</p><div className="space-y-8 mt-10">{post.sections.map(section=><section key={section.heading}><h2 className="text-2xl font-extrabold text-slate-900">{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph} className="text-slate-600 leading-relaxed mt-3">{paragraph}</p>)}</section>)}</div><aside className="bg-gradient-to-r from-purple-50 to-emerald-50 border border-purple-100 rounded-2xl p-6 mt-12"><h2 className="text-xl font-extrabold text-slate-900">Talk to Elite Friends</h2><p className="text-sm text-slate-600 mt-2">Your AI astrologer and trusted digital friend for thoughtful conversations about love, career, and daily life.</p><Link to="/" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-700 mt-4">Choose your companion <ArrowRight className="w-4 h-4"/></Link></aside></article></main>;
}
